@SimpleMarket_HostAddress = http://localhost:5182

# get product
GET {{SimpleMarket_HostAddress}}/api/Market/products/1
Accept: application/json
###

# get products
GET {{SimpleMarket_HostAddress}}/api/Market/products/all/20
Accept: application/json
###

# post product
POST {{SimpleMarket_HostAddress}}/api/Market/products
Content-Type: application/json

{
  "name": "apple1",
  "price": 121,
  "count": 300
}
###
# delete product
DELETE {{SimpleMarket_HostAddress}}/api/Market/products/1

#####



# get order
GET {{SimpleMarket_HostAddress}}/api/Market/orders
Accept: application/json
###

# get orders
GET {{SimpleMarket_HostAddress}}/api/Market/orders/all/20
Accept: application/json
###

# post order
POST {{SimpleMarket_HostAddress}}/api/Market/orders
Content-Type: application/json

[
  {
    "productId": 1,
    "count": 10
  },
  {
    "productId": 2,
    "count": 100
  }
]

###
# delete order
DELETE {{SimpleMarket_HostAddress}}/api/Market/orders/1
